"""
simulate_strategy_trades_two_close.py

Purpose:
- Load historical stock price data from CSV (generated by stock_scraper.py)
- Apply the TWO CLOSE alternative technical strategy:
    - Buy when Low > EMA21 for 3+ days followed by an up day
    - Sell when we get TWO closes below EMA21 (exit on second close)
- Simulate trades using a starting balance of $67,000 on a user-defined start date
- Track compounding performance by reinvesting entire balance each trade
- Track additional metrics: Keltner Channel upper bands, max high since buy, % above sell threshold
- Export:
    1. Each ticker's full strategy data and trade log into its own Excel file
    2. One-row summary per ticker into a master summary Excel file
"""
import pandas as pd
import warnings
import os

# === Setup ===
warnings.simplefilter(action="ignore", category=FutureWarning)
os.makedirs("output", exist_ok=True)

# === User Configuration ===
# Format: [("signal_ticker", "trade_ticker"), ...]
# signal_ticker: ticker to generate buy/sell signals from
# trade_ticker: ticker to actually trade
# For same ticker strategy, use: ("HOOD", "HOOD")
# For cross-ticker strategy, use: ("^IXIC", "TQQQ")
ticker_pairs = [("TSLA", "TSLA")]
starting_balance = 67000
start_date = "2020-01-01"

# === Summary Collector ===
summaries = []

# === Loop through ticker pairs ===
for signal_ticker, trade_ticker in ticker_pairs:
    signal_file = f"output/{signal_ticker.replace('^', '')}_price_data.csv"
    trade_file = f"output/{trade_ticker}_price_data.csv"
    output_file = f"output/{signal_ticker.replace('^', '')}_{trade_ticker}_21ema_two_close_strategy_result.xlsx"

    # Step 1: Load and filter signal ticker data
    try:
        signal_df = pd.read_csv(signal_file)
    except FileNotFoundError:
        print(f"⚠️ Signal file not found: {signal_file}. Skipping {signal_ticker} -> {trade_ticker}.")
        continue

    # Step 2: Load and filter trade ticker data  
    try:
        trade_df = pd.read_csv(trade_file)
    except FileNotFoundError:
        print(f"⚠️ Trade file not found: {trade_file}. Skipping {signal_ticker} -> {trade_ticker}.")
        continue

    # Process signal ticker data
    signal_df["Date"] = pd.to_datetime(signal_df["Date"])
    signal_df.set_index("Date", inplace=True)
    signal_df = signal_df[signal_df.index >= start_date]

    for col in ["Open", "High", "Low", "Close"]:
        signal_df[col] = pd.to_numeric(signal_df[col], errors="coerce")
    signal_df.dropna(subset=["Open", "High", "Low", "Close"], inplace=True)

    # Process trade ticker data
    trade_df["Date"] = pd.to_datetime(trade_df["Date"])
    trade_df.set_index("Date", inplace=True)
    trade_df = trade_df[trade_df.index >= start_date]

    for col in ["Open", "High", "Low", "Close"]:
        trade_df[col] = pd.to_numeric(trade_df[col], errors="coerce")
    trade_df.dropna(subset=["Open", "High", "Low", "Close"], inplace=True)

    # Create a map of trade ticker prices by date for quick lookup
    trade_prices = {}
    for date, row in trade_df.iterrows():
        trade_prices[date] = {
            'Open': row['Open'],
            'High': row['High'], 
            'Low': row['Low'],
            'Close': row['Close']
        }

    print(f"📊 Processing {signal_ticker} -> {trade_ticker}")
    print(f"   Signal data: {len(signal_df)} rows from {signal_df.index[0].date()} to {signal_df.index[-1].date()}")
    print(f"   Trade data:  {len(trade_df)} rows from {trade_df.index[0].date()} to {trade_df.index[-1].date()}")

    # Step 3: Compute indicators on SIGNAL ticker
    signal_df["EMA21"] = signal_df["Close"].ewm(span=21, adjust=False).mean()
    signal_df["sell_threshold"] = signal_df["EMA21"] * 0.998
    signal_df["low_above_ema"] = signal_df["Low"] > signal_df["EMA21"]
    signal_df["up_day"] = signal_df["Close"] > signal_df["Close"].shift(1)
    signal_df["close_below_ema"] = signal_df["Close"] < signal_df["EMA21"]

    # Keltner Channel Upper Bands (on signal ticker)
    tr = signal_df[["High", "Low", "Close"]].copy()
    tr["prev_close"] = tr["Close"].shift(1)
    tr["tr"] = tr[["High", "prev_close"]].max(axis=1) - tr[["Low", "prev_close"]].min(axis=1)
    signal_df["RangeMA"] = tr["tr"].rolling(window=10).mean()
    signal_df["Upper_2ATR"] = signal_df["EMA21"] + 2 * signal_df["RangeMA"]
    signal_df["Upper_3ATR"] = signal_df["EMA21"] + 3 * signal_df["RangeMA"]
    signal_df["Upper_4ATR"] = signal_df["EMA21"] + 4 * signal_df["RangeMA"]

    # New: Distance of daily high vs ATR bands (in %)
    signal_df["pct_high_vs_3ATR"] = ((signal_df["High"] - signal_df["Upper_3ATR"]) / signal_df["Upper_3ATR"]) * 100
    signal_df["pct_high_vs_4ATR"] = ((signal_df["High"] - signal_df["Upper_4ATR"]) / signal_df["Upper_4ATR"]) * 100

    # Initialize signal tracking columns
    signal_df["signal"] = 0
    signal_df["trade_ticker_price"] = None
    signal_df["max_high_since_buy"] = None
    signal_df["pct_above_sell_threshold"] = None

    # Step 4: TWO CLOSE Strategy Signal Logic (using signal ticker)
    streak = 0
    in_wait_mode = False
    position_open = False
    last_buy_index = None
    consecutive_closes_below_ema = 0

    for i in range(2, len(signal_df)):
        current_date = signal_df.index[i]
        
        # Skip if no trade ticker data available for this date
        if current_date not in trade_prices:
            continue
            
        # Get trade ticker price for this date
        trade_price = trade_prices[current_date]['Close']
        signal_df.at[current_date, "trade_ticker_price"] = trade_price

        if position_open:
            # TWO CLOSE SELL LOGIC (based on signal ticker)
            if signal_df.iloc[i]["close_below_ema"]:
                consecutive_closes_below_ema += 1
                
                # Exit on second consecutive close below EMA21
                if consecutive_closes_below_ema >= 2:
                    signal_df.at[signal_df.index[i], "signal"] = -1
                    position_open = False
                    consecutive_closes_below_ema = 0
                    in_wait_mode = False

                    if last_buy_index is not None:
                        max_high = signal_df.loc[signal_df.index[last_buy_index]:signal_df.index[i], "High"].max()
                        signal_df.at[signal_df.index[i], "max_high_since_buy"] = round(max_high, 2)
                        pct = ((max_high - signal_df.iloc[i]["sell_threshold"]) / signal_df.iloc[i]["sell_threshold"]) * 100
                        signal_df.at[signal_df.index[i], "pct_above_sell_threshold"] = round(pct, 2)

                    streak = 0
                    continue
            else:
                # Reset counter if close is not below EMA21
                consecutive_closes_below_ema = 0

        # Track streak of Low > EMA21 (buy logic - based on signal ticker)
        if signal_df.iloc[i]["low_above_ema"]:
            streak += 1
        elif signal_df.iloc[i]["Close"] < signal_df.iloc[i]["EMA21"]:
            streak = 0
            in_wait_mode = False

        # Buy condition (based on signal ticker)
        if streak >= 3 and not position_open:
            if signal_df.iloc[i]["up_day"]:
                signal_df.at[signal_df.index[i], "signal"] = 1
                position_open = True
                last_buy_index = i
                streak = 0
                in_wait_mode = False
                consecutive_closes_below_ema = 0
            else:
                in_wait_mode = True

        elif in_wait_mode and signal_df.iloc[i]["up_day"] and signal_df.iloc[i]["low_above_ema"] and not position_open:
            signal_df.at[signal_df.index[i], "signal"] = 1
            position_open = True
            last_buy_index = i
            streak = 0
            in_wait_mode = False
            consecutive_closes_below_ema = 0

        elif not signal_df.iloc[i]["low_above_ema"] and signal_df.iloc[i]["Close"] < signal_df.iloc[i]["EMA21"]:
            streak = 0
            in_wait_mode = False

    # Step 5: Simulate Trades (using trade ticker prices)
    balance = starting_balance
    buy_price = None
    buy_date = None
    shares = None
    trade_count = 0
    final_status = "Fully Closed"
    trades = []

    for i in range(len(signal_df)):
        row = signal_df.iloc[i]
        date = signal_df.index[i]
        signal = row["signal"]
        
        # Skip if no trade ticker data for this date
        if date not in trade_prices:
            continue
            
        trade_close_price = trade_prices[date]['Close']

        if signal == 1:
            # Buy (using trade ticker price)
            buy_price = trade_close_price
            buy_date = date
            shares = int(balance // buy_price)
            invested = shares * buy_price
            start_balance_snapshot = balance
            balance = round(balance - invested, 2)
            trade_count += 1

        elif signal == -1 and buy_price is not None:
            # Sell (using trade ticker price)
            sell_price = trade_close_price
            proceeds = round(shares * sell_price, 2)
            balance = round(balance + proceeds, 2)

            trades.append({
                "Buy Date": buy_date.date(),
                "Buy Price": round(buy_price, 2),
                "Shares": shares,
                "Sell Date": date.date(),
                "Sell Price": round(sell_price, 2),
                "Starting Balance": round(start_balance_snapshot, 2),
                "Cash After Trade": balance
            })

            buy_price = None
            buy_date = None
            shares = None
            trade_count += 1

    # Handle open position at end of data
    if buy_price is not None:
        final_status = "Still in Position"
        last_date = signal_df.index[-1]
        if last_date in trade_prices:
            last_close = trade_prices[last_date]['Close']
            proceeds = round(shares * last_close, 2)
            balance = round(balance + proceeds, 2)

            trades.append({
                "Buy Date": buy_date.date(),
                "Buy Price": round(buy_price, 2),
                "Shares": shares,
                "Sell Date": last_date.date(),
                "Sell Price": round(last_close, 2),
                "Starting Balance": round(start_balance_snapshot, 2),
                "Cash After Trade": balance,
                "Note": "Still in position"
            })
            trade_count += 1

    # Step 6: Prepare Output
    df_output = signal_df[[
        "Open", "High", "Low", "Close", "EMA21", "sell_threshold",
        "low_above_ema", "up_day", "close_below_ema", "signal", "trade_ticker_price", "max_high_since_buy",
        "pct_above_sell_threshold", "Upper_2ATR", "Upper_3ATR", "Upper_4ATR",
        "pct_high_vs_3ATR", "pct_high_vs_4ATR"
    ]].round(2)

    percent_gain = round(((balance - starting_balance) / starting_balance) * 100, 2)

    summary_row = {
        "Signal Ticker": signal_ticker,
        "Trade Ticker": trade_ticker,
        "Start Date": pd.to_datetime(start_date).date(),
        "End Date": signal_df.index[-1].date(),
        "Starting Balance": starting_balance,
        "Final Balance": round(balance, 2),
        "Percent Gain": percent_gain,
        "Total Trades": trade_count,
        "Status": final_status
    }

    summaries.append(summary_row)

    # Step 7: Save Excel file for this ticker pair with detailed trades as main sheet
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        # Sheet 1: Detailed Trades (main sheet)
        trades_detailed = []
        for i, trade in enumerate(trades, 1):
            # Calculate holding period
            buy_date = pd.to_datetime(trade["Buy Date"])
            sell_date = pd.to_datetime(trade["Sell Date"])
            holding_days = (sell_date - buy_date).days
            
            # Calculate return percentage
            return_pct = ((trade["Sell Price"] - trade["Buy Price"]) / trade["Buy Price"]) * 100
            
            trades_detailed.append({
                "Trade #": i,
                "Signal Ticker": signal_ticker,
                "Trade Ticker": trade_ticker,
                "Buy Date": trade["Buy Date"],
                "Sell Date": trade["Sell Date"],
                "Holding Days": holding_days,
                "Buy Price": trade["Buy Price"],
                "Sell Price": trade["Sell Price"],
                "Shares": trade["Shares"],
                "Return %": round(return_pct, 2),
                "Profit/Loss": round((trade["Sell Price"] - trade["Buy Price"]) * trade["Shares"], 2),
                "Beginning Balance": trade["Starting Balance"],
                "Balance After": trade["Cash After Trade"],
                "Status": trade.get("Note", "Completed")
            })
        
        trades_df = pd.DataFrame(trades_detailed)
        trades_df.to_excel(writer, sheet_name="Detailed Trades", index=False)
        
        # Sheet 2: Summary (matching your format exactly)
        summary_df = pd.DataFrame([summary_row])
        summary_df.to_excel(writer, sheet_name="Summary", index=False)
        
        # Sheet 3: Strategy Data (technical indicators)
        df_output.to_excel(writer, sheet_name="Strategy Data", index=True)

    print(f"✅ {signal_ticker} -> {trade_ticker} two close strategy complete. Saved to: {output_file}")
    print(f"   Total trades: {trade_count}, Final balance: ${balance:,.2f}, Return: {percent_gain:.2f}%\n")

# Step 8: Save master summary file
summary_df = pd.DataFrame(summaries)
summary_df.to_excel("output/21ema_two_close_strategy_summary.xlsx", index=False)
print("\n📊 Master summary saved to: output/21ema_two_close_strategy_summary.xlsx")