import fs from "fs";
import path from "path";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// Read once at module-init time. The build-info.json file is generated by
// next.config.ts at build time and ships with the deploy artifact. Reading
// at module-init (rather than on every request) is fine because the file
// can't change for the lifetime of this server process — and avoids the
// per-request filesystem read.
//
// Falls back to NEXT_PUBLIC_BUILD_ID then "unknown" if the file is missing
// (e.g., local dev before `next build` has been run for the first time).
const BUILD_INFO_PATH = path.join(process.cwd(), "public", "build-info.json");
let BUILD_ID = "unknown";
try {
  const raw = fs.readFileSync(BUILD_INFO_PATH, "utf-8");
  const parsed = JSON.parse(raw);
  if (parsed && typeof parsed.buildId === "string") {
    BUILD_ID = parsed.buildId;
  }
} catch {
  BUILD_ID = process.env.NEXT_PUBLIC_BUILD_ID || "unknown";
}

export async function GET() {
  return new Response(
    JSON.stringify({ buildId: BUILD_ID }),
    {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "no-store, max-age=0, must-revalidate",
      },
    },
  );
}
